apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-saw2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-saw2@sha256:1ca605fa3d6283a56ab8c2a2825f36e3895c71683c5872fbdc9bbdd7c079054d
        name: my-nodejs
        resources: {}
status: {}
